<?php

use Illuminate\Database\Seeder;
use App\Element;
class ElementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $element = new Element();
		$element->name='Gaji Pokok';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='ALPHA';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Tetap';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='THR';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan ASTEK';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Potongan Tunj ASTEK';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Premi BPJS Kesehatan Employer';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Pensiun 3';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan BPJS Kesehatan';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Kacamata';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan BPJS TK JP Employee';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Asuransi Jiwa';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Lembur';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Asuransi Jiwa';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Obat';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Obat';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Iuran Koperasi';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Koperasi';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Kost';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Makan';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Tunjangan Kost';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Makan Lembur';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Perabot';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Tunjangan Perabot';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Kacamata';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Lain Lain Gross';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Lain Lain Net';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Lain Lain';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Transport';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Transport Lembur';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Transport Libur';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Penempatan';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Ponsel';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Operational Head Allowance';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan OPEX';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Incentive ACP';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan COC';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Incentive C2C';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Bunga';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Kehadiran';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Sumbangan Marriage';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Sumbangan Condolence';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Cuti';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Driver';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Multiguna';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Operation';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Incentive';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Rapel Tetap';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Potongan Reguler';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Pinjaman COC';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Loan Medical';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Asuransi';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan COM';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Soft Loan';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan LCOP';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Potongan Asuransi CMOP';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Incentive Remedial';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Incentive Tarikan';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Koreksi Incentive';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Bonus';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Recovery';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Konsistensi';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Potongan Pensiun';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Pensiun 2';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Rapel Gaji Pokok';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Perawatan';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Bagasi';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Pindah';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Incentive GAP';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Bunga Asuransi';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Pindah';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Rumah';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Bagasi';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Transport Lembur';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Pendidikan Anak';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Perjalanan Cuti';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Perawatan';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Sumbangan';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Cuti';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Transport';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Makan Lembur';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Makan';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Pendidikan Anak';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Umroh';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Perjalanan Cuti';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Asuransi Kecelakaan Kerja';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka Flexi';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Uang Muka ACP';
		$element->type='Deduction';
		$element->save();
		$element = new Element();
		$element->name='Tunjangan Asuransi Kecelakaan Kerja';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
	  	$element->name='Tunjangan Rumah';
	  	$element->type='Allowance';
	  	$element->save();
		$element = new Element();
		$element->name='Tunjangan Pajak';
		$element->type='Allowance';
		$element->save();
		$element = new Element();
		$element->name='Potongan Pajak';
		$element->type='Deduction';
		$element->save();
		
    }
}
