<?php

use Illuminate\Database\Seeder;
use App\HomeBase;
class HomeBasesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hb = new HomeBase();
		$hb->name='Ambon';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Balikpapan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Banda Aceh';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bandar Lampung';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bandung';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Banjar';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Banjarbaru';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Banjarmasin';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Batam';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Batu';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bau-Bau';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bekasi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bengkulu';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bima';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Binjai';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bitung';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Blitar';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bogor';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bontang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Bukittinggi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Cilegon';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Cimahi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Cirebon';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Denpasar';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Depok';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='DKI Jakarta';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Dumai';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Gorontalo';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Jambi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Jayapura';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Kediri';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Kendari';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Kotamobagu';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Kupang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Langsa';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Lhokseumawe';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Lubuklinggau';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Madiun';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Magelang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Makassar';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Malang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Manado';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Mataram';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Medan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Metro';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Meulaboh';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Mojokerto';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Padang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Padang Sidempuan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Padangpanjang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pagaralam';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Palangkaraya';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Palembang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Palopo';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Palu';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pangkalpinang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Parepare';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pariaman';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pasuruan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Payakumbuh';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pekalongan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pekanbaru';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pematangsiantar';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Pontianak';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Prabumulih';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Probolinggo';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Purwokerto';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sabang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Salatiga';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Samarinda';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sawahlunto';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Semarang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Serang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sibolga';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Singkawang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Solok';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sorong';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Subulussalam';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sukabumi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Sungai Penuh';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Surabaya';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Surakarta';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tangerang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tangerang Selatan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tanjungbalai';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tanjungpinang';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tarakan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tasikmalaya';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tebingtinggi';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tegal';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Ternate';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tidore Kepulauan';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tomohon';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Tual';
		$hb->save();
		$hb = new HomeBase();
		$hb->name='Yogyakarta';
		$hb->save();
    }
}
